development:
  adapter: postgresql
  encoding: unicode
  database: wlc
  pool: 5
  username: stephenbrewer
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: wlc_test
  pool: 5
  username: stephenbrewer
  password:
